// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run DDL, which shouldn't go through a PgBouncer transaction-mode
    // pooler — use the direct/unpooled connection when available (Neon's Vercel
    // integration provides DATABASE_URL_UNPOOLED alongside the pooled DATABASE_URL
    // the app uses at runtime), falling back to DATABASE_URL for local dev.
    url: process.env["DATABASE_URL_UNPOOLED"] || process.env["DATABASE_URL"],
  },
});
